// Theme configuration for the application

export const themes = {
  'solar-dusk': {
    name: 'Solar Dusk',
    description: 'Warm, earthy tones with orange accents',
    fonts: {
      sans: 'Oxanium, sans-serif',
      serif: 'Merriweather, serif',
      mono: 'Fira Code, monospace'
    },
    radius: '0.3rem',
    spacing: '0.25rem',
    light: {
      background: '#fdfbf7',
      foreground: '#4a3b33',
      card: '#f8f4ee',
      cardForeground: '#4a3b33',
      popover: '#f8f4ee',
      popoverForeground: '#4a3b33',
      primary: '#b45309',
      primaryForeground: '#ffffff',
      secondary: '#e4c090',
      secondaryForeground: '#57534e',
      muted: '#f1e9da',
      mutedForeground: '#78716c',
      accent: '#f2daba',
      accentForeground: '#57534e',
      destructive: '#991b1b',
      destructiveForeground: '#ffffff',
      border: '#e4d9bc',
      input: '#e4d9bc',
      ring: '#b45309',
      shadowColor: 'hsl(28 18% 25%)',
    },
    dark: {
      background: '#1c1917',
      foreground: '#f5f5f4',
      card: '#292524',
      cardForeground: '#f5f5f4',
      popover: '#292524',
      popoverForeground: '#f5f5f4',
      primary: '#f97316',
      primaryForeground: '#ffffff',
      secondary: '#57534e',
      secondaryForeground: '#e7e5e4',
      muted: '#201d1a',
      mutedForeground: '#a8a29e',
      accent: '#1e4252',
      accentForeground: '#e7e5e4',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#44403c',
      input: '#44403c',
      ring: '#f97316',
      shadowColor: 'hsl(0 0% 5%)',
    }
  },
  'clean-slate': {
    name: 'Clean Slate',
    description: 'Modern, minimal design with orange accents',
    fonts: {
      sans: 'Inter, sans-serif',
      serif: 'Merriweather, serif',
      mono: 'JetBrains Mono, monospace'
    },
    radius: '0.5rem',
    spacing: '0.25rem',
    light: {
      background: '#ffffff',
      foreground: '#0f172a',
      card: '#f8fafc',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      primary: '#EA580C',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      accent: '#fed7aa',
      accentForeground: '#EA580C',
      destructive: '#ef4444',
      destructiveForeground: '#fef2f2',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#EA580C',
      shadowColor: 'hsl(215 25% 27%)',
    },
    dark: {
      background: '#020617',
      foreground: '#f8fafc',
      card: '#0f172a',
      cardForeground: '#f8fafc',
      popover: '#0f172a',
      popoverForeground: '#f8fafc',
      primary: '#f97316',
      primaryForeground: '#ffffff',
      secondary: '#1e293b',
      secondaryForeground: '#f8fafc',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#1e293b',
      accentForeground: '#f8fafc',
      destructive: '#7f1d1d',
      destructiveForeground: '#fef2f2',
      border: '#1e293b',
      input: '#1e293b',
      ring: '#f97316',
      shadowColor: 'hsl(215 25% 27%)',
    }
  }
};

export const defaultTheme = 'clean-slate';
