#!/usr/bin/env node

/**
 * JVZoo Integration Setup Script
 * Generates boilerplate IPN handler code for your chosen framework
 * 
 * Usage: node setup_ipn_endpoint.js [framework]
 * Frameworks: express, nextjs, fastapi
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

const templates = {
  express: {
    filename: 'ipn-handler.js',
    content: `/**
 * JVZoo IPN Handler for Express.js
 * Generated by JVZoo Integration Setup Script
 */

require('dotenv').config();
const express = require('express');
const crypto = require('crypto');
const bodyParser = require('body-parser');

const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

// Configuration
const JVZOO_SECRET_KEY = process.env.JVZOO_SECRET_KEY;

// Product mapping
const PRODUCT_MAPPING = {
  'YOUR_PRODUCT_ID': {
    name: 'Your Product Name',
    features: ['feature1', 'feature2'],
    internalId: 'your-product-id'
  }
};

// Verify IPN
function verifyIPN(ipnData, secretKey) {
  const { ctransaction, ctransamount, cproditem, cverify } = ipnData;
  
  if (!ctransaction || !ctransamount || !cproditem || !cverify) {
    return false;
  }
  
  const hash = crypto
    .createHash('sha1')
    .update(\`\${secretKey}|\${ctransaction}|\${ctransamount}|\${cproditem}\`)
    .digest('hex')
    .toUpperCase();
  
  return hash === cverify.toUpperCase();
}

// IPN Handler
app.post('/ipn', async (req, res) => {
  // Always return 200 OK
  res.status(200).send('OK');
  
  try {
    const ipnData = req.body;
    
    console.log('IPN Received:', {
      transaction: ipnData.ctransaction,
      type: ipnData.ctransaction_type,
      email: ipnData.ccustemail
    });
    
    // Verify IPN
    if (!verifyIPN(ipnData, JVZOO_SECRET_KEY)) {
      console.error('IPN verification failed');
      return;
    }
    
    // TODO: Implement your business logic here
    switch (ipnData.ctransaction_type) {
      case 'SALE':
        // Handle new sale
        console.log('Processing sale...');
        break;
      case 'RFND':
        // Handle refund
        console.log('Processing refund...');
        break;
      case 'CGBK':
        // Handle chargeback
        console.log('Processing chargeback...');
        break;
      default:
        console.warn('Unknown transaction type:', ipnData.ctransaction_type);
    }
    
  } catch (error) {
    console.error('IPN processing error:', error);
  }
});

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(\`JVZoo IPN server running on port \${PORT}\`);
});
`
  },
  
  nextjs: {
    filename: 'pages/api/jvzoo/ipn.js',
    content: `/**
 * JVZoo IPN Handler for Next.js API Routes
 * Generated by JVZoo Integration Setup Script
 */

import crypto from 'crypto';

// Configuration
const JVZOO_SECRET_KEY = process.env.JVZOO_SECRET_KEY;

// Product mapping
const PRODUCT_MAPPING = {
  'YOUR_PRODUCT_ID': {
    name: 'Your Product Name',
    features: ['feature1', 'feature2'],
    internalId: 'your-product-id'
  }
};

// Verify IPN
function verifyIPN(ipnData, secretKey) {
  const { ctransaction, ctransamount, cproditem, cverify } = ipnData;
  
  if (!ctransaction || !ctransamount || !cproditem || !cverify) {
    return false;
  }
  
  const hash = crypto
    .createHash('sha1')
    .update(\`\${secretKey}|\${ctransaction}|\${ctransamount}|\${cproditem}\`)
    .digest('hex')
    .toUpperCase();
  
  return hash === cverify.toUpperCase();
}

export default async function handler(req, res) {
  // Only accept POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }
  
  // Always return 200 OK to JVZoo
  res.status(200).send('OK');
  
  try {
    const ipnData = req.body;
    
    console.log('IPN Received:', {
      transaction: ipnData.ctransaction,
      type: ipnData.ctransaction_type,
      email: ipnData.ccustemail
    });
    
    // Verify IPN
    if (!verifyIPN(ipnData, JVZOO_SECRET_KEY)) {
      console.error('IPN verification failed');
      return;
    }
    
    // TODO: Implement your business logic here
    switch (ipnData.ctransaction_type) {
      case 'SALE':
        // Handle new sale
        console.log('Processing sale...');
        // await processSale(ipnData);
        break;
      case 'RFND':
        // Handle refund
        console.log('Processing refund...');
        // await processRefund(ipnData);
        break;
      case 'CGBK':
        // Handle chargeback
        console.log('Processing chargeback...');
        // await processChargeback(ipnData);
        break;
      default:
        console.warn('Unknown transaction type:', ipnData.ctransaction_type);
    }
    
  } catch (error) {
    console.error('IPN processing error:', error);
  }
}

export const config = {
  api: {
    bodyParser: true
  }
};
`
  },
  
  fastapi: {
    filename: 'ipn_handler.py',
    content: `"""
JVZoo IPN Handler for FastAPI
Generated by JVZoo Integration Setup Script
"""

import os
import hashlib
from fastapi import FastAPI, Request, BackgroundTasks
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime

app = FastAPI(title="JVZoo Integration API")

# Configuration
JVZOO_SECRET_KEY = os.getenv("JVZOO_SECRET_KEY")

# Product mapping
PRODUCT_MAPPING = {
    "YOUR_PRODUCT_ID": {
        "name": "Your Product Name",
        "features": ["feature1", "feature2"],
        "internal_id": "your-product-id"
    }
}

class IPNData(BaseModel):
    ctransaction: str
    ctransaction_type: str
    ccustemail: EmailStr
    ccustname: str
    cproditem: str
    ctransamount: str
    ctransreceipt: Optional[str] = None
    cverify: str

def verify_ipn(ipn_data: dict, secret_key: str) -> bool:
    """Verify IPN authenticity using SHA-1 hash"""
    try:
        transaction = ipn_data.get('ctransaction', '')
        amount = ipn_data.get('ctransamount', '')
        product_id = ipn_data.get('cproditem', '')
        verify_hash = ipn_data.get('cverify', '')
        
        if not all([transaction, amount, product_id, verify_hash]):
            return False
        
        data = f"{secret_key}|{transaction}|{amount}|{product_id}"
        calculated_hash = hashlib.sha1(data.encode()).hexdigest().upper()
        
        return calculated_hash == verify_hash.upper()
    except Exception as e:
        print(f"Verification error: {e}")
        return False

async def process_ipn(ipn_data: dict):
    """Process IPN in background"""
    try:
        print(f"IPN Received: {ipn_data.get('ctransaction')} - {ipn_data.get('ctransaction_type')}")
        
        # Verify IPN
        if not verify_ipn(ipn_data, JVZOO_SECRET_KEY):
            print("IPN verification failed")
            return
        
        # TODO: Implement your business logic here
        transaction_type = ipn_data.get('ctransaction_type')
        
        if transaction_type == 'SALE':
            # Handle new sale
            print("Processing sale...")
            # await process_sale(ipn_data)
        elif transaction_type == 'RFND':
            # Handle refund
            print("Processing refund...")
            # await process_refund(ipn_data)
        elif transaction_type == 'CGBK':
            # Handle chargeback
            print("Processing chargeback...")
            # await process_chargeback(ipn_data)
        else:
            print(f"Unknown transaction type: {transaction_type}")
            
    except Exception as e:
        print(f"IPN processing error: {e}")

@app.post("/ipn", response_class=PlainTextResponse)
async def jvzoo_ipn(
    request: Request,
    background_tasks: BackgroundTasks
):
    """JVZoo IPN endpoint"""
    # Always return 200 OK immediately
    form_data = await request.form()
    ipn_data = dict(form_data)
    
    # Process IPN in background
    background_tasks.add_task(process_ipn, ipn_data)
    
    return "OK"

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "ok",
        "timestamp": datetime.utcnow().isoformat()
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`
  }
};

const envTemplates = {
  express: `# JVZoo Configuration
JVZOO_SECRET_KEY=your_secret_key_here
LICENSE_SECRET=your_license_secret_here

# Database
DATABASE_URL=mongodb://localhost:27017/jvzoo_integration
# or for PostgreSQL:
# DATABASE_URL=postgresql://user:password@localhost:5432/jvzoo_db

# Application
PORT=3000
APP_URL=https://yourdomain.com

# Email Service
SENDGRID_API_KEY=your_sendgrid_api_key
FROM_EMAIL=noreply@yourdomain.com
`,
  
  nextjs: `# JVZoo Configuration
JVZOO_SECRET_KEY=your_secret_key_here
LICENSE_SECRET=your_license_secret_here

# Supabase
NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_anon_key
SUPABASE_SERVICE_ROLE_KEY=your_service_role_key

# Application
NEXT_PUBLIC_APP_URL=https://yourdomain.com

# Email Service (Resend)
RESEND_API_KEY=your_resend_api_key
FROM_EMAIL=noreply@yourdomain.com
`,
  
  fastapi: `# JVZoo Configuration
JVZOO_SECRET_KEY=your_secret_key_here
LICENSE_SECRET=your_license_secret_here

# Database
DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/jvzoo_db

# Application
APP_URL=https://yourdomain.com

# Email SMTP
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your_email@gmail.com
SMTP_PASSWORD=your_app_password
FROM_EMAIL=noreply@yourdomain.com
`
};

async function main() {
  console.log('\\n=== JVZoo Integration Setup ===\\n');
  
  const framework = await question('Choose framework (express/nextjs/fastapi): ');
  
  if (!templates[framework]) {
    console.error('Invalid framework. Choose: express, nextjs, or fastapi');
    rl.close();
    return;
  }
  
  const outputDir = await question('Output directory (default: ./jvzoo-setup): ') || './jvzoo-setup';
  
  // Create directory
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  // Write main file
  const template = templates[framework];
  const filePath = path.join(outputDir, template.filename);
  const fileDir = path.dirname(filePath);
  
  if (!fs.existsSync(fileDir)) {
    fs.mkdirSync(fileDir, { recursive: true });
  }
  
  fs.writeFileSync(filePath, template.content);
  console.log(\`✓ Created \${template.filename}\`);
  
  // Write .env template
  const envPath = path.join(outputDir, '.env.example');
  fs.writeFileSync(envPath, envTemplates[framework]);
  console.log('✓ Created .env.example');
  
  // Write README
  const readme = \`# JVZoo Integration

Generated using JVZoo Integration Setup Script

## Setup

1. Copy \`.env.example\` to \`.env\`
2. Fill in your JVZoo secret key and other credentials
3. Install dependencies
4. Run the application

## Framework: \${framework}

\${framework === 'express' ? \`
### Install dependencies
\\\`\\\`\\\`bash
npm install express body-parser crypto dotenv
\\\`\\\`\\\`

### Run
\\\`\\\`\\\`bash
node ipn-handler.js
\\\`\\\`\\\`
\` : framework === 'nextjs' ? \`
### Install dependencies
\\\`\\\`\\\`bash
npm install crypto
\\\`\\\`\\\`

### Run
\\\`\\\`\\\`bash
npm run dev
\\\`\\\`\\\`
\` : \`
### Install dependencies
\\\`\\\`\\\`bash
pip install fastapi uvicorn python-dotenv
\\\`\\\`\\\`

### Run
\\\`\\\`\\\`bash
uvicorn ipn_handler:app --reload
\\\`\\\`\\\`
\`}

## Configure JVZoo

Set your IPN URL in JVZoo product settings:
- Express: \\\`https://yourdomain.com/ipn\\\`
- Next.js: \\\`https://yourdomain.com/api/jvzoo/ipn\\\`
- FastAPI: \\\`https://yourdomain.com/ipn\\\`

## Next Steps

1. Update PRODUCT_MAPPING with your actual JVZoo product IDs
2. Implement database logic for user and license creation
3. Add email notification logic
4. Test with JVZoo test IPNs
5. Deploy to production

## Documentation

See the JVZoo Integration Skill documentation for complete implementation guides.
\`;
  
  fs.writeFileSync(path.join(outputDir, 'README.md'), readme);
  console.log('✓ Created README.md');
  
  console.log(\`\\n✅ Setup complete!\\n\`);
  console.log(\`Files created in: \${path.resolve(outputDir)}\`);
  console.log(\`\\nNext steps:\`);
  console.log(\`1. cd \${outputDir}\`);
  console.log(\`2. Copy .env.example to .env and fill in your credentials\`);
  console.log(\`3. Install dependencies (see README.md)\`);
  console.log(\`4. Update PRODUCT_MAPPING with your product IDs\`);
  console.log(\`5. Run the application\\n\`);
  
  rl.close();
}

main().catch(console.error);
